FROM listmonk/listmonk:latest
ARG PORT
ARG ADMIN_PASSWORD
ARG ADMIN_USERNAME
ARG PGDATABASE
ARG PGHOST
ARG PGPASSWORD
ARG PGPORT
ARG PGUSER
ENV PORT=$PORT
ENV ADMIN_PASSWORD=$ADMIN_PASSWORD
ENV ADMIN_USERNAME=$ADMIN_USERNAME
ENV PGDATABASE=$PGDATABASE
ENV PGHOST=$PGHOST
ENV PGPASSWORD=$PGPASSWORD
ENV PGPORT=$PGPORT
ENV PGUSER=$PGUSER
RUN ./listmonk --idempotent --yes --upgrade || ./listmonk --install --yes --upgrade
